# Hotel Demand Forecasting

## Business Scope & Benefits

The hotel operations of VGT are a significant part of its business and any efficiencies in this area have the potential to make large contributions to overall profitability. The profit contribution from individual hotels can be maximised by ensuring revenue is as high as possible whilst at the same time minimising a hotel's operating costs. One way to do this is to provide a hotel's management team with the tools to carry out reliable demand forecasting.

Hotel demand forecasting is the prediction of the demand for rooms and related hotel services to help a hotel's management team determine pricing, staffing and marketing strategies [@johansson2022]. If the demand for hotel rooms can be reliably forecast then this enables:

-   ßDynamic Pricing - Adjust future prices in response to forecast demand. When high demand is expected then future room rates can be increased; when low demand is expected then discounts can be offered or packages can be advertised. And marketing strategies can be determined to respond to the demand forecasts
-   Staffing Levels - Hotel staffing can be adjusted to maintain customer service levels but not over staff when demand is expected to be lower
-   Inventory Management - Similarly inventory can be adjusted, for example catering supplies maintained just sufficient to meet the forecast number of customers using catering facilities.

There are many factors that will influence the demand for hotel rooms, some may remain stable whilst others are less so and will vary over time or in response to external factors, these include:

-   Location & Market - Is the hotel a budget or a boutique hotel? Is is in a business district, near a beach or a ski resort etc. Are customers mainly business travellers or tourists?
-   Economic - Macro level impact from the state of the economy
-   Local Competition - Competition with local hotels
-   Seasonality - When are the high and low seasons? Is it a summer or a winter resort? What are the local weather patterns and seasons. Are there weather related attractions?
-   Local Events - When are any local festivities, sports events, school holidays, religious events, music conferences, business conferences?

### Occupancy & Revenue Indicators

An important indicator of demand is the occupancy rate [@jeffrey1994] and [@fha2023] which is simply the percentage of the total rooms occupied for a given time period. The occupancy rate varies across the industry but a target of 60% to 80% is typical.

Occupancy is used alongside revenue related indicators to provide a measure of revenue health, the three main indicators (for a given time period, eg daily) are:

-   Occupancy Rate (OCC%) - Percentage of available rooms that are occupied, or expected to be occupied
-   Average Daily Rate (ADR) - Average revenue per room occupied, across all room price bands
-   Revenue Per Available Room (RevPAR) - Revenue reflecting all available rooms. Calculated by: OCC% \* ADR. A good overall indicator of revenue.

### Forecasting Occupancy & Business Benefits

The time period used for forecasting will vary depending on the objectives desired [@lighthouse2024] and [@lighthouse2023] for example:

-   Short Term - Forecast occupancy for next month so room pricing can be adjusted appropriately.
-   Long-term - Forecast occupancy for next year so price bands and packages can be set, marketing strategies defined and required staffing levels determined.

To recap, if occupancy (and the associated revenue indicators) can be reliably forecast then plans can be put in place to maximise revenue by adjusting pricing and marketing strategies and controlling costs by flexing staffing and inventory levels.

## Data Analysis Approach

At VGT, no rigorous forecasting is currently in place so to begin with a relatively simple approach will be implemented in a small number of hotels. If the benefits of this are confirmed, then it can then be extended in sophistication using more complex forecasting models and for longer time periods. It can then be implemented across all hotels in VGT.

The objective of this first step is to establish a model that can be used to forecast the daily OCC% at an individual hotel for the coming month, ie the forecast is for 30 to 40 days in the future. The forecast will then be used by hotel's management team to: i) adopt dynamic pricing; ii) execute supporting short-term marketing; iii) fine-tune staffing rotas and holiday leave for the coming weeks. This should improve the efficiency of the hotel's operations by increasing room bookings whilst ensuring staffing costs are controlled at an appropriate level.

### Forecasting Model & Data Required

The scope of the envisaged forecasting model is to calculate a month of daily OCC% for each room category in an hotel. The output of the forecast model will be provided in spreadsheet form so that the hotel management team can manually make adjustments to try to improve revenue and staffing levels. The actual occupancy and revenue can then be tracked against the forecast throughout the month in order to assess how accurate the forecasting model is and to help refine it.

*Forecasting Model Data*

The data required for the forecasting model is the last 4 years of daily room occupancy. In this analysis a single hotel with two classes of room (standard and premium) will be used. A 4 year history of daily room bookings was selected with 3 years used for training and 1 year for validation. This length of history was chosen as a starting point because a previous occupancy study [@phumchusri2023] found that the choice could be quite dependent on the scenario; however, there needs to be a a balance of too short and missing seasonality vs too long and not being sufficiently responsive. @phumchusri2023 also found that using 4 years history of daily occupancy to forecast 2 to 8 weeks was a good approach.

The specific data required is:

-   For an individual hotel and each room category (standard and premium)
-   Daily
-   Room capacity
-   Room rate
-   Rooms occupied

*Tracking Spreadsheets*

The data comprising the revenue forecasting and tracking spreadsheet is:

-   Forecast OCC% (derived from the forecasting model)
-   Daily room rates by room category that can be manually adjusted
-   Daily Revenue, ADR, RevPAR (derived from the OCC% and room rates)
-   Special events, a facility to mark local events that may impact demand. For example, sports events, concerts, conference, unusual weather forecasts
-   Actual OCC%, Revenue, ADR, RevPAR

The data provided for the staffing forecasting spreadsheet is:

-   Forecast OCC% (from the forecasting model)
-   Averaged staff requirements per room
-   Staffing levels (derived from the OCC%)
-   Actual staffing levels

### Techniques Considered

There are several potential tools that can be used with historical time series data to forecast future occupancy rates, ranging from established 'simpler' techniques such as linear regression through to more sophisticated machine learning and neural network models [@huang2022]. However, given the relative infancy of Data Science at VGT, the use of more sophisticated tools will be prioritised for future work. In this investigation, the following techniques will be examined:

1.  Ordinary Least Squares (OLS) linear regression
2.  ARIMA, SARIMA - Use to fully incorporate seasonality
3.  SARIMAX - If exogenous factors need to be accounted for

#### OLS Linear Regression

Investigating techniques for reliably identifying the factors influencing hotel occupancy has been ongoing for several years. See @andrew1990 and @jeffrey1994 for earlier work focusing on the use of regression analysis of time series data. Although it is likely that the nature of hotel business means that occupancy will be seasonal, linear regression will still be investigated first.

#### ARIMA, SARIMA

Occupancy forecasting using ARIMA using factors such as room capacity and marketing expenditure has successfully been used [@chow1998]. A comparison of forecasting methods [@weatherford2003] included historical time series analysis of occupancy using ARIMA. The best time period used was not clear and it is a balance of too short and missing seasonality vs too long and not being sufficiently responsive. Also the best analysis method appears to depend on the characteristics of individual hotels and hotel chains. Using a SARIMA approach using 4 years history of daily occupancy to forecast 2 to 8 weeks was found to be a strong approach [@phumchusri2023].

#### SARIMAX

Due to limitations in processing capacity for daily data a SARIMAX model was not created. But see @sec-ARIMA-conclusions for next steps.

## Simulated Data Analysis

### Data Summary

A dataset was created to simulate the data as defined in the earlier section. The data elements are shown in the tables below and in more detail at @sec-Demand_Appendix.

{{< embed ../../Notebooks_Data_Analysis/demand_analysis.ipynb#csv_file_types >}}

{{< embed ../../Notebooks_Data_Analysis/demand_analysis.ipynb#csv_file_stats >}}

### Time Series Characteristics

The occupancy time series for the two categories of room are shown in the figure below. This indicates that the occupancy has a strong seasonality with an annual peak and trough; there are also regular spikes to full capacity bookings. The premium room occupancy hits maximum and zero occupancy on several occasions.

{{< embed ../../Notebooks_Data_Analysis/demand_analysis.ipynb#generated_time_series >}}

The two occupancy time series were examined further (see detail at @sec-Demand_Appendix) using lag plots, ACF plots and ADF tests which indicated autocorrelation, annual seasonality and a positive trend. Differencing was also completed to confirm non-stationarity. Finally a decomposition was completed and this confirmed the seasonality and trend, see the figures below for standard and premium rooms.

{{< embed ../../Notebooks_Data_Analysis/demand_analysis.ipynb#decomposition >}}

{{< embed ../../Notebooks_Data_Analysis/demand_analysis.ipynb#decomposition-prem >}}

\clearpage

### OLS Linear Regression {#sec-plot}

Given the strong seasonality, linear regression is unlikely to be a good model for forecasting, however a regression fit was calculated to double-check. See the plot below which shows that the fit lines could not reliably provide a forecast and even show a downward trend. And the Durban Watson statistics are less than 2 which confirms evidence of autocorrelation.

{{< embed ../../Notebooks_Data_Analysis/demand_analysis.ipynb#olsregression >}}

### ARIMA, SARIMA

### SARIMAX

Test see earlier @sec-plot

and earlier @fig-test

### Execution - Data Analysis

-   Use simulated data to carry out analysis

-   Show the results, forecasts ....

-   ***?? carry out PACF to determine the autoregressive order for ARIMA etc***

## Conclusions & Next Steps {#sec-ARIMA-conclusions}

### Findings

xxx

### Next Steps

-   ?? how are special events impactful on revenue predictions, can these be better used in the forecast going forward or in an improved forecasting model
-   ?? recent flight searches, enquiries ... for the area

xxxx

-   ?? track actual OCC% etc and compare to forecast to allow model refinement as well as intra-month fine tuning
-   ?? Get competitors OCC% to compare and improve forecasting models
-   ?? automate the manual pricing changes etc, ie no need for manual adjustment of the forecast spreadsheet
-   xx LightGBM ..
-   xx CNN, LSTM, RNN ...
-   xx transformers, LLM ..

xxx improvements

-   ?? isolate pricing strategies and refine the model
-   ?? identify the main parameters / impacts on the forecasting ... what are the demand indicators?
-   ?? categorisation of customers, families, demographics etc, business, tourist
-   ?? identify correlations with holiday patterns, events ......
-   ?? identify seasonal bands, high, low, shoulder etc
-   ?? identify links between revenue and room price bands ...