project:
  type: book

book:
  title: "V.Ger Travel Company - An Analysis"
  subtitle: "ITNPBD4 Assignment"
  author: "Student: 2710017"
  date: 13 January 2025
  date-format: "DD MMMM YYYY"

  chapters:
    - index.qmd             # Have to have this index.qmd, rest can be .ipynb or .qmd .... use it as a summary
    - _chapters/hotel_demand_forecasting.qmd
    - _chapters/customer_satisfaction.qmd
    - _chapters/references.qmd
  appendices:
    - _chapters/appendix_demand.qmd
    - _chapters/appendix_sarima.qmd
    - _chapters/appendix_customer_satisfaction.qmd

bibliography: references.bib
csl: harvard-cite-them-right.csl

format:
  pdf:
    include-in-header: include-in-header.tex
    documentclass: scrreport  
    papersize: a4
    fontsize: 11pt

    toc-title: "Table of Contents"
    toc-depth: 2
    number-sections: true
    number-depth: 2
    indent: false
    geometry:
    - inner=2.5cm
    - outer=2.5cm
    - top=2cm
    - bottom=4cm
    - headsep=22pt
    - headheight=11pt
    - footskip=33pt
    - ignorehead
    - ignorefoot
    - heightrounded
